#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

. /etc/profile
. ~/z.sh

# Kill the lag
export KEYTIMEOUT=1


# Git repo for dot management
alias config='/usr/bin/git --git-dir=/home/dagnachew/.cfg --work-tree=/home/dagnachew'

# VPN
alias vpn='sudo openvpn /etc/openvpn/CA_Montreal.conf & '

# Network restart
alias netrestart='sudo systemctl restart NetworkManager.service'

# Virtual environement
. /usr/bin/virtualenvwrapper.sh

