#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

export EDITOR="vim"
export KEYTIMEOUT=1
export TERM=xterm-256color
export BROWSER="chromium"


HISTFILE=~/.zsh_history
SAVEHIST=50000
HISTSIZE=50000

setopt append_history # Allow multiple terminal sessions to all append to one zsh command history
setopt extended_history # save timestamp of command and duration


# tmux
#[ -n "$TMUX " ] && export TERM=screen-256color

. /etc/profile
. ~/z.sh

# Import color scheme from 'wal'
export PATH=$PATH:/data/packages/wal
(wal -r &)

# Git repo for dot management
alias config='/usr/bin/git --git-dir=/home/dagnachew/.cfg --work-tree=/home/dagnachew'

# VPN
alias vpn='sudo openvpn /etc/openvpn/CA_Montreal.conf & '

# Network restart
alias netrestart='sudo systemctl restart NetworkManager.service'

# Chromium cache
alias chromium='chromium --disk-cache-dir=/tmp/chromium'

# Firefox tmpfs
alias firefox='~/bin/firefox &'

# Virtual environement

##  My Power Level 9K config
##



source ~/.zprezto/zsh-autoenv/autoenv.zsh
