# Shell variables
# Generated by 'wal'
wallpaper='/data/wallpapers/japan-lanterns-street-culture.jpg'

# Special
background='#1c1d24'
foreground='#c6b1bb'
cursor='#c6b1bb'

# Colors
color0='#1c1d24'
color1='#5F5868'
color2='#A33A52'
color3='#9B5A5B'
color4='#D86B66'
color5='#A68778'
color6='#F49775'
color7='#c6b1bb'
color8='#8a7b82'
color9='#5F5868'
color10='#A33A52'
color11='#9B5A5B'
color12='#D86B66'
color13='#A68778'
color14='#F49775'
color15='#c6b1bb'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
